# Taken from: https://packaging.python.org/en/latest/appveyor.html
# and from: https://bitbucket.org/pygame/pygame/pull-request/45/create-python-wheel-builds-using-appveyor/diff
# For now considering only Python 2.7, looking to support soon Python 2.6
# and Python 3 in the future

environment:
    matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

init:

    - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
    - "set PATH=%PATH%;%PYTHON%;%PYTHON%\\Scripts;C:\\Program Files (x86)\\LilyPond\\usr\\bin"
    - "pip install nose"
    - "pip install -r requirements.txt"
    - "set HOME=%APPVEYOR_BUILD_FOLDER%"
    - ps:
        (new - object net.webclient).DownloadFile('http://download.linuxaudio.org/lilypond/binaries/mingw/lilypond-2.18.2-1.mingw.exe', 'lilypond.exe')
    - ps:
        start / wait - verb runas lilypond.exe / S

build:
    off

test_script:
    - "nosetests --logging-level=WARNING"
